# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext0 = "#a6adc8"
# overlay0 = "#6c7086"
# surface0 = "#313244"

# Mostly default format with fil moved
# Which is equivalent to
format = """
$username\
$hostname\
$localip\
$kubernetes\
$directory\
$docker_context\
$deno\
$gleam\
$golang\
$lua\
$nodejs\
$php\
$python\
$ruby\
$rust\
$swift\
$terraform\
$direnv\
$env_var\
$cmd_duration\
$jobs\
$battery\
$status\
$package\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$shell\
$character"""
# ${custom.jspackage_detect}\

[gcloud]
disabled = true


[fill]
symbol = ' '

[docker_context]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "#f5e0dc" # mauve

[jobs]
symbol = ""
style = "bold #eba0ac"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
up_to_date = '✓'
# format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#89dceb" # sky

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#6c7086" # overlay0 (subtle gray tone)

[git_commit]
tag_symbol = '  '

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[golang]
symbol = " "
format = '[$symbol](bold cyan)[$version](#b4befe bold) '

[hostname]
ssh_symbol = " "

[rust]
symbol = "󱘗 "
format = '[$symbol](red bold)[$version](#b4befe bold)'

[lua]
symbol = " "
format = '[$symbol](#89b4fa)[$version](#b4befe bold)'



[custom.jspackage_detect]
detect_files = ['package.json'] # can specify filters but wildcards are not supported
command = 'cat package.json | jq .name' # shows output of command
style = "bold #eba0ac"
format = '[$output]($style)'

[nodejs]
# symbol = ' '
symbol = " "
format = '[$symbol](#f9e2af)[$version](bold green) '


[python]
symbol = ' '
format = '[$symbol](#f9e2af)[$version](bold green) '

# [direnv]
# disabled = false

[directory]
# style = "#f5e0dc"
