#!/bin/bash
#
# Convert HiRes video into 1080p (both landscape and portrait) using ffmpeg

if [ -z "$1" ]; then
  echo "Usage: ./convert_video.sh <path-to-video-folder>"
  exit 1
fi

video_dir="$1"
out_video_dir="/Users/rahuldesar/testing/haram/ffmpeg"

if [ ! -d "$video_dir" ]; then
  echo "Error: Directory $video_dir does not exist."
  exit 1
fi

for video in "$video_dir"/*.{mp4,mkv,avi,mov,flv,webm}; do
  if [ -f "$video" ]; then
    filename=$(basename "$video" | sed 's/\(.*\)\..*/\1/')

    video_width=$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of default=noprint_wrappers=1:nokey=1 "$video")
    video_height=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of default=noprint_wrappers=1:nokey=1 "$video")

    if [ "$video_width" -gt "$video_height" ]; then
      scale="scale=-1:1080"
    else
      scale="scale=1080:-1"
    fi

    ffmpeg -i "$video" -c:v hevc_videotoolbox -vtag hvc1 -vf "$scale" -b:v 3M -c:a copy "$out_video_dir/${filename}_1080p.mp4"

    # ffmpeg -i "$video" -c:v libx265 -vtag hvc1 -vf "$scale" -crf 20 -c:a copy "$out_video_dir/${filename}_1080p.mp4"
    #
    echo "$scale"

    echo "Converted $video to ${filename}_1080p.mp4"
  fi
done
