#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(
    (
      find \
        ~/.config \
        ~/.config/custom-nvim/* \
        ~/.config/nvim-snippets/* \
        ~/Developer/Personal/* \
        ~/Developer/Personal/career \
        ~/Developer/Personal/helpers \
        ~/Developer/Personal/learning \
        ~/Developer/Personal/learning/algorithms \
        ~/Developer/Personal/learning/css \
        ~/Developer/Personal/learning/css \
        ~/Developer/Personal/learning/design-patterns \
        ~/Developer/Personal/learning/drizzle-orm \
        ~/Developer/Personal/learning/fso \
        ~/Developer/Personal/learning/golang \
        ~/Developer/Personal/learning/golang/gopher \
        ~/Developer/Personal/learning/golang/tutorial \
        ~/Developer/Personal/learning/golang/web-app \
        ~/Developer/Personal/learning/golang/web-frameworks \
        ~/Developer/Personal/learning/homelab \
        ~/Developer/Personal/learning/htmx \
        ~/Developer/Personal/learning/lua/love2d \
        ~/Developer/Personal/learning/mega-repo \
        ~/Developer/Personal/learning/mega-repo/lang \
        ~/Developer/Personal/learning/mooc \
        ~/Developer/Personal/learning/nvim \
        ~/Developer/Personal/learning/rust \
        ~/Developer/Personal/learning/rust-by-examples \
        ~/Developer/Personal/learning/rust-packages \
        ~/Developer/Personal/learning/todo-k8 \
        ~/Developer/Personal/learning/tui \
        ~/Developer/Personal/learning/vagrant \
        ~/Developer/Personal/open-source \
        ~/Developer/Personal/open-source/neovim \
        ~/Developer/Personal/projects \
        ~/Developer/Personal/projects/advent-of-code \
        ~/Developer/Personal/projects/project-chrome-extensions \
        ~/Developer/Personal/projects/golang \
        ~/Developer/Personal/reference/golang \
        ~/Developer/Personal/reference/lua \
        ~/Developer/Workspace/* \
        ~/Developer/vaults \
        ~/Documents \
        -mindepth 1 -maxdepth 1 \( -type d -o -type l \) ! -name "node_modules" ! -name ".bare" \
        ;
      # find \
      #   -mindepth 1 -maxdepth 2 -type d ! -path '*/.*' ! -name "node_modules" \
      #   ;
      find ~ -mindepth 1 -maxdepth 1 -type d ! -path '*/.*'
    ) |
      xargs stat --format="%X %n" |
      sort -nr |
      cut -d' ' -f2- | uniq | fzf
  )
fi

#
# ~/Developer/Personal/2024 ~/Developer/Personal/aws ~/Developer/Personal/career ~/Developer/Personal/docs ~/Developer/Personal/learning ~/Developer/Personal/practice ~/Developer/Personal/projects ~/Developer/Personal/reference ~/Developer/Personal/selected ~/Developer/Personal/servers ~/Developer/Personal/temp ~/Developer/Personal/test-apps ~/Developer/Personal/testing

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  # tmux new-session -ds $selected_name -c $selected
  tmuxinator sessionizer $selected_name $selected
fi

tmux switch-client -t $selected_name
