-- TODO: use when updating nvim
--
-- return {
-- 	"Bekaboo/dropbar.nvim",
--
-- 	dependencies = {
-- 		"nvim-telescope/telescope-fzf-native.nvim",
-- 	},
--
-- 	config = function() end,
-- }
--
return {}
