-- return {
--   "akinsho/toggleterm.nvim",
--   version = "*",
--
--   config = function()
--     require("toggleterm").setup({
--       open_mapping = [[<leader>`]],
--       start_in_insert = true,
--       insert_mappings = false,
--       direction = "float",
--       shading_factor = 2,
--       close_on_exit = true,
--       auto_scroll = true,
--     })
--   end
-- }
--
return {}
